pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT_ID = '428847003845'
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        FRONTEND_REPO = "efootball25-frontend"
        BACKEND_REPO  = "efootball25-backend"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/TanmoyDas02/cloud-native-3tier-app.git'
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
                '''
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                docker build -t $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG app/efootball25/backend
                docker build --build-arg VITE_API_URL="" -t $ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG app/efootball25/frontend
                '''
            }
        }

        stage('Push Docker Images') {
            steps {
                sh '''
                docker push $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG
                docker push $ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh '''
                kubectl apply -f kubernetes/mysql.yaml
                kubectl apply -f kubernetes/backend.yaml
                kubectl apply -f kubernetes/frontend.yaml

                kubectl set image deployment/backend backend=$ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG
                kubectl set image deployment/frontend frontend=$ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG

                kubectl rollout status deployment/backend
                kubectl rollout status deployment/frontend
                '''
            }
        }

        stage('Verify') {
            steps {
                sh '''
                kubectl get pods
                kubectl get svc
                '''
            }
        }
    }
}